version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: jelena_bachelor_db
    volumes:
      - ./db:/var/lib/postgresql/data
  back:
    build: back/.
    image: bachelor_project_rest_back
    privileged: true
    env_file: 
      - ./back/.env
    restart: unless-stopped
    container_name: jelena_bachelor_back
    volumes:
      - ./back/assignments:/app/assignments
    ports:
      - 8022:80
    links:
      - db
  front:
    build: front/.
    image: bachelor_project_rest_front
    restart: unless-stopped
    container_name: jelena_bachelor_front
    ports:
      - 8021:80
    links:
      - back
