version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: jelena_bachelor_db
    volumes:
      - ./db:/var/lib/postgresql/data
  back:
    build: back/.
    env_file: 
      - ./back/.env
    restart: unless-stopped
    container_name: jelena_bachelor_back
    volumes:
      - ./back/assignments:/app/assignments
    ports:
      - "8000:80"
    links:
      - db
  front:
    build: front/.
    restart: unless-stopped
    container_name: jelena_bachelor_front
    ports:
      - 8080:80
    links:
      - back