version: '3'

services:
  db:
    image: postgres:11
    restart: unless-stopped
    container_name: jelena_bachelor_db
    env_file:
      - ./back/.env
    volumes:
      - db:/var/lib/postgresql/data
  back:
    build: back/.
    image: bachelor_project_rest_back
    privileged: true
    env_file:
      - ./back/.env
    restart: unless-stopped
    container_name: jelena_bachelor_back
    volumes:
      - assignments:/app/students/data/assignments
      - /mnt/fixtures:/app/students/data/fixtures
    ports:
      - 8022:80
  front:
    build: front/.
    image: bachelor_project_rest_front
    restart: unless-stopped
    container_name: jelena_bachelor_front
    ports:
      - 8021:80

volumes:
  assignments:
  db:
