version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: jelena_bachelor_db
    volumes:
       - ./db:/var/lib/postgresql/data
  web:
    build: .
    env_file: 
      - ".env"
    restart: unless-stopped
    container_name: jelena_bachelor_web
    ports:
      - "8000:80"
    links:
      - db