# Generated by Django 2.1.5 on 2019-03-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='filename',
            field=models.CharField(max_length=40),
            preserve_default=False,
        ),
    ]
