# Generated by Django 2.1.5 on 2019-03-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_assignment_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_added',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
