# Generated by Django 2.1.5 on 2019-07-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190519_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='result',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
