# Generated by Django 2.1.5 on 2020-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20190715_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='task_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]