# Generated by Django 2.1.5 on 2020-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_assignment_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturefile',
            name='fixturetext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
